#include "codegen.h"

/* Code shape for a program (System V AMD64 ABI):
 *
 *   main:                       ; on entry rsp % 16 == 8 (return addr pushed)
 *       push rbp                ; rsp % 16 == 0  -> aligned for calls
 *       mov  rbp, rsp
 *       lea  rdi, [rip + .LstrN]   ; arg0 = pointer to NUL-terminated string
 *       call puts@PLT              ; puts writes the string plus '\n'
 *       ...one lea/call pair per print statement...
 *       xor  eax, eax           ; return 0 (also zero-extends into rax)
 *       pop  rbp
 *       ret
 *
 * rdi and rax are caller-saved, so nothing else needs preserving. puts'
 * return value is ignored. Because puts stops at the first NUL byte, the
 * lexer rejects NUL characters in strings. */

static void emit_string_directive(Buf *out, const char *s, size_t n) {
    buf_printf(out, "    .asciz \"");
    for (size_t i = 0; i < n; i++) {
        unsigned char c = (unsigned char)s[i];
        if (c == '"' || c == '\\') buf_printf(out, "\\%c", c);
        else if (c >= 0x20 && c < 0x7f) buf_byte(out, c);
        else buf_printf(out, "\\%03o", c); /* octal escape: \n -> \012 */
    }
    buf_printf(out, "\"\n");
}

/* Writes a human-readable copy of the source string into an asm comment. */
static void emit_comment_string(Buf *out, const char *s, size_t n) {
    for (size_t i = 0; i < n && i < 60; i++) {
        unsigned char c = (unsigned char)s[i];
        if (c == '\n') buf_printf(out, "\\n");
        else if (c == '\t') buf_printf(out, "\\t");
        else if (c >= 0x20 && c < 0x7f) buf_byte(out, c);
        else buf_byte(out, '?');
    }
    if (n > 60) buf_printf(out, "...");
}

void codegen_program(const Program *prog, Buf *out) {
    buf_printf(out, "# Generated by luma from %s -- do not edit.\n", prog->source_path);
    buf_printf(out, "    .intel_syntax noprefix\n\n");

    buf_printf(out, "    .section .rodata\n");
    for (size_t i = 0; i < prog->len; i++) {
        const Stmt *s = &prog->stmts[i];
        buf_printf(out, ".Lstr%zu:    # \"", i);
        emit_comment_string(out, s->value.str, s->value.str_len);
        buf_printf(out, "\"\n");
        emit_string_directive(out, s->value.str, s->value.str_len);
    }

    buf_printf(out, "\n    .text\n");
    buf_printf(out, "    .globl main\n");
    buf_printf(out, "    .type main, @function\n");
    buf_printf(out, "main:\n");
    buf_printf(out, "    push rbp\n");
    buf_printf(out, "    mov rbp, rsp\n");
    for (size_t i = 0; i < prog->len; i++) {
        const Stmt *s = &prog->stmts[i];
        switch (s->kind) {
        case STMT_PRINT:
            buf_printf(out, "    # %s:%d: print\n", prog->source_path, s->line);
            buf_printf(out, "    lea rdi, [rip + .Lstr%zu]\n", i);
            buf_printf(out, "    call puts@PLT\n");
            break;
        }
    }
    buf_printf(out, "    xor eax, eax\n");
    buf_printf(out, "    pop rbp\n");
    buf_printf(out, "    ret\n");
    buf_printf(out, "    .size main, .-main\n\n");
    buf_printf(out, "    .section .note.GNU-stack\n");
}
